"""Build a small server-side track-label index from DB InfraGO OpenStation.

Download separately (never during app startup/build):
curl -L --compressed https://bahnhof.de/daten/netex -o /tmp/openstation.xml
python3 scripts/import-platforms.py /tmp/openstation.xml
Only explicit railPlatform PlateCode values are used, never digits from IDs.
"""
import hashlib
import json
from pathlib import Path
import sys
from urllib.parse import unquote
import xml.etree.ElementTree as ET

NS = {"n": "http://www.netex.org.uk/netex"}
PREFIX = "https://id.vdv.de/dhid/"


def dhid(element):
    for kv in element.findall("n:keyList/n:KeyValue", NS):
        if kv.findtext("n:Key", namespaces=NS) == "NORMALIZED_ID_URI":
            uri = kv.findtext("n:Value", default="", namespaces=NS)
            if uri.startswith(PREFIX):
                return unquote(uri[len(PREFIX):])
    return None


def extract(path):
    stations, published = {}, None
    for _, node in ET.iterparse(path, events=["end"]):
        if node.tag == "{" + NS["n"] + "}PublicationTimestamp":
            published = node.text
        if node.tag != "{" + NS["n"] + "}StopPlace":
            continue
        for quay in node.findall("n:quays/n:Quay", NS):
            key = dhid(quay)
            plate = (quay.findtext("n:PlateCode", default="", namespaces=NS)).strip()
            if (not key or not key.startswith("de:") or len(key.split(":")) < 5
                    or not plate or len(plate) > 30
                    or quay.findtext("n:QuayType", namespaces=NS) != "railPlatform"):
                continue
            station = ":".join(key.split(":")[:3])
            entries = stations.setdefault(station, {})
            if key in entries and entries[key] != plate:
                raise ValueError("Conflicting platform labels for " + key)
            entries[key] = plate
        node.clear()
    if not published or not stations:
        raise ValueError("No OpenStation platform data")
    return {"source": "https://bahnhof.de/daten/netex", "license": "CC0-1.0",
            "publishedAt": published,
            "stations": {s: dict(sorted(q.items())) for s, q in sorted(stations.items())}}


if __name__ == "__main__":
    source = Path(sys.argv[1])
    data = extract(source)
    digest = hashlib.sha256()
    with source.open("rb") as f:
        for block in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(block)
    data["sourceSha256"] = digest.hexdigest()
    target = Path(__file__).resolve().parents[1] / "lib/platform-data.mjs"
    target.write_text("// Generated by scripts/import-platforms.py; DB InfraGO OpenStation, CC0.\n"
                      + "export const platformRegistry=" + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n")
    print(f"{len(data['stations'])} stations, {sum(map(len, data['stations'].values()))} track labels, {target.stat().st_size} bytes")
